import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class HamburgerServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        
        try (PrintWriter out = response.getWriter()) {
            out.println("<!DOCTYPE html>");
            out.println("<html lang=\"en\">");
            out.println("<head>");
            out.println("  <meta charset=\"UTF-8\">");
            out.println("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
            out.println("  <title>Hamburger Menu Example</title>");
            out.println("  <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;700&display=swap\" rel=\"stylesheet\">");
            out.println("  <style>");
            out.println("    /* Global styles */");
            out.println("    * { margin: 0; padding: 0; box-sizing: border-box; font-family: 'Poppins', sans-serif; }");
            out.println("    header {");
            out.println("      background: #333;");
            out.println("      color: white;");
            out.println("      display: flex;");
            out.println("      justify-content: space-between;");
            out.println("      align-items: center;");
            out.println("      padding: 10px 20px;");
            out.println("      position: relative;");
            out.println("    }");
            out.println("    nav ul {");
            out.println("      list-style: none;");
            out.println("      display: flex;");
            out.println("      gap: 20px;");
            out.println("    }");
            out.println("    nav ul li a {");
            out.println("      color: white;");
            out.println("      text-decoration: none;");
            out.println("    }");
            out.println("    /* Hamburger ikona (sakrivena na desktopu) */");
            out.println("    .hamburger {");
            out.println("      display: none;");
            out.println("      flex-direction: column;");
            out.println("      cursor: pointer;");
            out.println("    }");
            out.println("    .hamburger span {");
            out.println("      height: 3px;");
            out.println("      width: 25px;");
            out.println("      background: white;");
            out.println("      margin-bottom: 5px;");
            out.println("      border-radius: 3px;");
            out.println("    }");
            out.println("    /* Mobile padajući meni */");
            out.println("    .mobile-menu {");
            out.println("      display: none;");
            out.println("      flex-direction: column;");
            out.println("      background: #333;");
            out.println("      position: absolute;");
            out.println("      top: 60px; /* ispod headera */");
            out.println("      width: 100%;");
            out.println("      left: 0;");
            out.println("    }");
            out.println("    .mobile-menu a {");
            out.println("      padding: 15px 20px;");
            out.println("      border-top: 1px solid #444;");
            out.println("      color: white;");
            out.println("      text-decoration: none;");
            out.println("    }");
            out.println("    .mobile-menu a:hover {");
            out.println("      background: #444;");
            out.println("    }");
            out.println("    /* Media query za mobilne uređaje */");
            out.println("    @media (max-width: 768px) {");
            out.println("      nav ul { display: none; }");
            out.println("      .hamburger { display: flex; }");
            out.println("    }");
            out.println("  </style>");
            out.println("</head>");
            out.println("<body>");
            out.println("  <header>");
            out.println("    <div class=\"logo\">Logo</div>");
            out.println("    <nav>");
            out.println("      <!-- Desktop navigacija -->");
            out.println("      <ul>");
            out.println("        <li><a href=\"#\">Home</a></li>");
            out.println("        <li><a href=\"#\">About</a></li>");
            out.println("        <li><a href=\"#\">Services</a></li>");
            out.println("        <li><a href=\"#\">Contact</a></li>");
            out.println("      </ul>");
            out.println("      <!-- Hamburger ikona (prikazuje se samo na mobilnim uređajima) -->");
            out.println("      <div class=\"hamburger\" onclick=\"toggleMobileMenu()\">");
            out.println("        <span></span>");
            out.println("        <span></span>");
            out.println("        <span></span>");
            out.println("      </div>");
            out.println("      <!-- Mobile padajući meni -->");
            out.println("      <div class=\"mobile-menu\" id=\"mobileMenu\">");
            out.println("        <a href=\"#\">Home</a>");
            out.println("        <a href=\"#\">About</a>");
            out.println("        <a href=\"#\">Services</a>");
            out.println("        <a href=\"#\">Contact</a>");
            out.println("      </div>");
            out.println("    </nav>");
            out.println("  </header>");
            out.println("  <script>");
            out.println("    function toggleMobileMenu() {");
            out.println("      var mobileMenu = document.getElementById('mobileMenu');");
            out.println("      if (mobileMenu.style.display === 'flex') {");
            out.println("        mobileMenu.style.display = 'none';");
            out.println("      } else {");
            out.println("        mobileMenu.style.display = 'flex';");
            out.println("      }");
            out.println("    }");
            out.println("  </script>");
            out.println("</body>");
            out.println("</html>");
        }
    }
}
